# SwiftLint Configuration for Ikigai
# https://github.com/realm/SwiftLint

# Paths to include in linting
included:
  - Sources
  - IkigaiApp
  - ActionExtension
  - ShareExtension
  - NotificationExtension
  - NotificationServiceExtension
  - MessageExtension
  - SpotlightExtension
  - WidgetExtension
  - WatchApp
  - Tests
  - AppClips

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Packages
  - .git
  - docs
  - fastlane
  - build

# Rules to disable
disabled_rules:
  - trailing_whitespace # Handled by SwiftFormat
  - line_length # Handled by SwiftFormat

# Rules to enable (opt-in rules)
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Custom rule configurations
array_init:
  severity: warning

closure_end_indentation:
  severity: warning

closure_spacing:
  severity: warning

collection_alignment:
  align_colons: true

contains_over_filter_count:
  severity: error

contains_over_filter_is_empty:
  severity: error

contains_over_first_not_nil:
  severity: error

cyclomatic_complexity:
  warning: 15
  error: 25

discouraged_object_literal:
  severity: warning

empty_count:
  severity: error

empty_string:
  severity: warning

enum_case_associated_values_count:
  warning: 5
  error: 6

explicit_init:
  severity: warning

extension_access_modifier:
  severity: warning

fatal_error_message:
  severity: warning

file_length:
  warning: 500
  error: 1000

first_where:
  severity: warning

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: warning

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

large_tuple:
  warning: 3
  error: 4

last_where:
  severity: warning

legacy_random:
  severity: error

literal_expression_end_indentation:
  severity: warning

modifier_order:
  preferred_modifier_order:
    - override
    - acl
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

number_separator:
  minimum_length: 5

object_literal:
  severity: warning

operator_usage_whitespace:
  severity: warning

overridden_super_call:
  severity: error

override_in_extension:
  severity: error

pattern_matching_keywords:
  severity: warning

prefer_self_type_over_type_of_self:
  severity: warning

private_action:
  severity: warning

private_outlet:
  severity: warning

prohibited_super_call:
  severity: error

reduce_into:
  severity: warning

redundant_nil_coalescing:
  severity: warning

redundant_type_annotation:
  severity: warning

single_test_class:
  severity: warning

sorted_first_last:
  severity: warning

static_operator:
  severity: warning

toggle_bool:
  severity: warning

trailing_comma:
  mandatory_comma: true

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

unavailable_function:
  severity: error

unneeded_parentheses_in_closure_argument:
  severity: warning

untyped_error_in_catch:
  severity: warning

vertical_parameter_alignment_on_call:
  severity: warning

vertical_whitespace:
  max_empty_lines: 2

vertical_whitespace_closing_braces:
  severity: warning

vertical_whitespace_opening_braces:
  severity: warning

xct_specific_matcher:
  severity: warning

yoda_condition:
  severity: warning

# Custom rules
custom_rules:
  # Encourage use of localized strings
  hardcoded_strings:
    name: "Hardcoded Strings"
    regex: '(Text|Label|Button|Alert|ActionSheet)\s*\(\s*"[^"]*"\s*\)'
    message: "Consider using localized strings instead of hardcoded text"
    severity: warning
    
  # Discourage force unwrapping in production code
  force_unwrap_production:
    name: "Force Unwrapping in Production"
    regex: '!\s*(?![=!])'
    match_kinds:
      - identifier
    message: "Consider using optional binding or guard statements instead of force unwrapping"
    severity: warning
    
  # Encourage proper documentation
  missing_documentation:
    name: "Missing Documentation"
    regex: '^(?!.*///).*\b(public|open)\s+(class|struct|enum|protocol|func|var|let)'
    message: "Public declarations should have documentation comments"
    severity: warning

# Reporter configuration
reporter: "xcode"